<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <RootNamespace>Invoicing.Api</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Invoicing.Contracts\Invoicing.Contracts.csproj" />
    <ProjectReference Include="..\Invoicing.Rendering\Invoicing.Rendering.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
    <PackageReference Include="Newtonsoft.Json" />
    <PackageReference Include="Polly.Extensions.Http" />
  </ItemGroup>

</Project>
