<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <RootNamespace>Warehouse.Stock.Api</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Warehouse.Stock.Application\Warehouse.Stock.Application.csproj" />
    <ProjectReference Include="..\Warehouse.Stock.Infrastructure\Warehouse.Stock.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
  </ItemGroup>

</Project>
