<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Rentals.Lending.Application</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Rentals.Contracts\Rentals.Contracts.csproj" />
    <ProjectReference Include="..\Rentals.Lending.Domain\Rentals.Lending.Domain.csproj" />
    <ProjectReference Include="..\Rentals.Messaging\Rentals.Messaging.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" />
  </ItemGroup>

</Project>
