<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Fx.Conversion.UnitTests</RootNamespace>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Fx.Conversion.Core\Fx.Conversion.Core.csproj" />
    <ProjectReference Include="..\..\src\Fx.Conversion.Rates\Fx.Conversion.Rates.csproj" />
    <ProjectReference Include="..\Fx.Conversion.TestSupport\Fx.Conversion.TestSupport.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CsCheck" />
    <PackageReference Include="Microsoft.Extensions.TimeProvider.Testing" />
    <PackageReference Include="NSubstitute" />
    <PackageReference Include="Shouldly" />
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="xunit.v3.mtp-off" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
    <None Update="Fixtures\*.xml" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
