apiVersion: v1
kind: Service
metadata:
  name: quellbrook-dispatch
  namespace: quellbrook-dispatch
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: quellbrook-dispatch
  ports:
    - name: http
      port: 80
      targetPort: http
