<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
    <CheckEolTargetFramework>false</CheckEolTargetFramework>
    <RootNamespace>Invoicing.ArchiveExporter</RootNamespace>
    <AssemblyName>invoicing-archive-export</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CsvHelper" />
    <PackageReference Include="iTextSharp.LGPLv2.Core" />
    <PackageReference Include="SharpZipLib" />
  </ItemGroup>

</Project>
