# Registry pull credential, encrypted with the cluster's sealed-secrets public key. Only the
# controller in the cluster holds the private key that can decrypt it.
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-pull
  namespace: depot-slots
spec:
  encryptedData:
    .dockerconfigjson: AgBwbPanyTU6x4xW8o2yQ3o1XLNVsQI89ybzXTvaOTSUT7yaDFaS0GGnB5lG/8OtU84V+Kx3Hinujeh+Do4hYZL7abfxKc42LwzPsYm5Bdc53Vp6pxn/mEM8MiJmxxhXbcFKTUf1DFaZqplTHJ5WXhWfXp+gZ4FLgzoJjvHCEi5CbgdyIMTZn072ojWrXYRhreTiPeEThH6ygl3U2atTTjfXzmXjfGgztRtqVQKxYd7MqrB2d/xLRBym3zNILLQguiKUS578C/5h03oGU1TTlXfj2gR/rcxM+xuJSe8GNjJp3jLZUJtSbakxr33UrHval0WQStmBAn9wThC8EpjVqF2wDs61RQoTymDANm3CQ/xrUiBeyQ8DWmBN+Gl/V8jTh7Sr+SUCJBU9xATytMy6mxjGEt40h0VMtv9aBHQuEmglw3H6Fw3PAOUldlA2NwBHJ7/mOaRnupS4BT5kPaxYXAQnbVwA88TMlkOe/OdCC06M413JqNzOddawo7RWugESpglKqJx3csz9Xr/0Epp+WZbAZOca32f09hPWs6AtA8dp2m94snJwLcoszMfp8FQakj5U2LppjykMYWhYBJkkbXEv949Cd34cp1x60lJZYCQiHeCRaJFo9sRL3Y7vH0del6PrLSJbnMtchItGKFp9HzFho8KCJ83iC+3HtHqJQMePIZosHbLlv5E8Q==
  template:
    metadata:
      name: ghcr-pull
      namespace: depot-slots
    type: kubernetes.io/dockerconfigjson
