/** One heading of the catalogue's browse vocabulary. */
export interface SubjectHeading {
  readonly code: string;
  readonly label: string;
  /** The broader heading the browse facet groups it under. */
  readonly broader: string;
  /** Sibling headings suggested next to it. */
  readonly related: readonly string[];
}

/** The subject-heading vocabulary used by the browse facet, as agreed by the cataloguing team. */
export const SUBJECT_HEADINGS: readonly SubjectHeading[] = [
  {
    code: 'AC-01',
    label: 'Painting',
    broader: 'Arts and crafts',
    related: ['Drawing', 'Art history'],
  },
  {
    code: 'AC-02',
    label: 'Drawing',
    broader: 'Arts and crafts',
    related: ['Sculpture', 'Painting'],
  },
  {
    code: 'AC-03',
    label: 'Sculpture',
    broader: 'Arts and crafts',
    related: ['Photography', 'Drawing'],
  },
  {
    code: 'AC-04',
    label: 'Photography',
    broader: 'Arts and crafts',
    related: ['Ceramics', 'Sculpture'],
  },
  {
    code: 'AC-05',
    label: 'Ceramics',
    broader: 'Arts and crafts',
    related: ['Knitting and crochet', 'Photography'],
  },
  {
    code: 'AC-06',
    label: 'Knitting and crochet',
    broader: 'Arts and crafts',
    related: ['Sewing', 'Ceramics'],
  },
  {
    code: 'AC-07',
    label: 'Sewing',
    broader: 'Arts and crafts',
    related: ['Woodworking', 'Knitting and crochet'],
  },
  {
    code: 'AC-08',
    label: 'Woodworking',
    broader: 'Arts and crafts',
    related: ['Calligraphy', 'Sewing'],
  },
  {
    code: 'AC-09',
    label: 'Calligraphy',
    broader: 'Arts and crafts',
    related: ['Art history', 'Woodworking'],
  },
  {
    code: 'AC-10',
    label: 'Art history',
    broader: 'Arts and crafts',
    related: ['Painting', 'Calligraphy'],
  },
  {
    code: 'CF-01',
    label: 'Picture books',
    broader: 'Children and families',
    related: ['Early readers', 'School life'],
  },
  {
    code: 'CF-02',
    label: 'Early readers',
    broader: 'Children and families',
    related: ['Parenting', 'Picture books'],
  },
  {
    code: 'CF-03',
    label: 'Parenting',
    broader: 'Children and families',
    related: ['Family activities', 'Early readers'],
  },
  {
    code: 'CF-04',
    label: 'Family activities',
    broader: 'Children and families',
    related: ["Children's poetry", 'Parenting'],
  },
  {
    code: 'CF-05',
    label: "Children's poetry",
    broader: 'Children and families',
    related: ['Fairy tales', 'Family activities'],
  },
  {
    code: 'CF-06',
    label: 'Fairy tales',
    broader: 'Children and families',
    related: ['Bedtime stories', "Children's poetry"],
  },
  {
    code: 'CF-07',
    label: 'Bedtime stories',
    broader: 'Children and families',
    related: ['School life', 'Fairy tales'],
  },
  {
    code: 'CF-08',
    label: 'School life',
    broader: 'Children and families',
    related: ['Picture books', 'Bedtime stories'],
  },
  {
    code: 'FH-01',
    label: 'Baking',
    broader: 'Food and home',
    related: ['Vegetarian cooking', 'Wine and drinks'],
  },
  {
    code: 'FH-02',
    label: 'Vegetarian cooking',
    broader: 'Food and home',
    related: ['Preserving', 'Baking'],
  },
  {
    code: 'FH-03',
    label: 'Preserving',
    broader: 'Food and home',
    related: ['Home repair', 'Vegetarian cooking'],
  },
  {
    code: 'FH-04',
    label: 'Home repair',
    broader: 'Food and home',
    related: ['Interior design', 'Preserving'],
  },
  {
    code: 'FH-05',
    label: 'Interior design',
    broader: 'Food and home',
    related: ['Budget cooking', 'Home repair'],
  },
  {
    code: 'FH-06',
    label: 'Budget cooking',
    broader: 'Food and home',
    related: ['Cleaning and organising', 'Interior design'],
  },
  {
    code: 'FH-07',
    label: 'Cleaning and organising',
    broader: 'Food and home',
    related: ['Wine and drinks', 'Budget cooking'],
  },
  {
    code: 'FH-08',
    label: 'Wine and drinks',
    broader: 'Food and home',
    related: ['Baking', 'Cleaning and organising'],
  },
  {
    code: 'GN-01',
    label: 'Gardening',
    broader: 'Gardening and nature',
    related: ['Vegetable growing', 'Wild flowers'],
  },
  {
    code: 'GN-02',
    label: 'Vegetable growing',
    broader: 'Gardening and nature',
    related: ['Birds', 'Gardening'],
  },
  {
    code: 'GN-03',
    label: 'Birds',
    broader: 'Gardening and nature',
    related: ['Wetlands', 'Vegetable growing'],
  },
  {
    code: 'GN-04',
    label: 'Wetlands',
    broader: 'Gardening and nature',
    related: ['Trees', 'Birds'],
  },
  {
    code: 'GN-05',
    label: 'Trees',
    broader: 'Gardening and nature',
    related: ['Insects', 'Wetlands'],
  },
  {
    code: 'GN-06',
    label: 'Insects',
    broader: 'Gardening and nature',
    related: ['Weather', 'Trees'],
  },
  {
    code: 'GN-07',
    label: 'Weather',
    broader: 'Gardening and nature',
    related: ['Seashore life', 'Insects'],
  },
  {
    code: 'GN-08',
    label: 'Seashore life',
    broader: 'Gardening and nature',
    related: ['Wild flowers', 'Weather'],
  },
  {
    code: 'GN-09',
    label: 'Wild flowers',
    broader: 'Gardening and nature',
    related: ['Gardening', 'Seashore life'],
  },
  {
    code: 'HW-01',
    label: 'Fitness',
    broader: 'Health and wellbeing',
    related: ['Nutrition', 'Running'],
  },
  {
    code: 'HW-02',
    label: 'Nutrition',
    broader: 'Health and wellbeing',
    related: ['Mental health', 'Fitness'],
  },
  {
    code: 'HW-03',
    label: 'Mental health',
    broader: 'Health and wellbeing',
    related: ['Sleep', 'Nutrition'],
  },
  {
    code: 'HW-04',
    label: 'Sleep',
    broader: 'Health and wellbeing',
    related: ['Yoga', 'Mental health'],
  },
  {
    code: 'HW-05',
    label: 'Yoga',
    broader: 'Health and wellbeing',
    related: ['First aid', 'Sleep'],
  },
  {
    code: 'HW-06',
    label: 'First aid',
    broader: 'Health and wellbeing',
    related: ['Ageing well', 'Yoga'],
  },
  {
    code: 'HW-07',
    label: 'Ageing well',
    broader: 'Health and wellbeing',
    related: ['Running', 'First aid'],
  },
  {
    code: 'HW-08',
    label: 'Running',
    broader: 'Health and wellbeing',
    related: ['Fitness', 'Ageing well'],
  },
  {
    code: 'H-01',
    label: 'Local history',
    broader: 'History',
    related: ['Maritime history', 'Social history'],
  },
  {
    code: 'H-02',
    label: 'Maritime history',
    broader: 'History',
    related: ['World War I', 'Local history'],
  },
  {
    code: 'H-03',
    label: 'World War I',
    broader: 'History',
    related: ['World War II', 'Maritime history'],
  },
  {
    code: 'H-04',
    label: 'World War II',
    broader: 'History',
    related: ['Ancient history', 'World War I'],
  },
  {
    code: 'H-05',
    label: 'Ancient history',
    broader: 'History',
    related: ['Industrial history', 'World War II'],
  },
  {
    code: 'H-06',
    label: 'Industrial history',
    broader: 'History',
    related: ['Family history and genealogy', 'Ancient history'],
  },
  {
    code: 'H-07',
    label: 'Family history and genealogy',
    broader: 'History',
    related: ['Social history', 'Industrial history'],
  },
  {
    code: 'H-08',
    label: 'Social history',
    broader: 'History',
    related: ['Local history', 'Family history and genealogy'],
  },
  {
    code: 'LL-01',
    label: 'Poetry',
    broader: 'Language and literature',
    related: ['Drama', 'Writing skills'],
  },
  {
    code: 'LL-02',
    label: 'Drama',
    broader: 'Language and literature',
    related: ['Short stories', 'Poetry'],
  },
  {
    code: 'LL-03',
    label: 'Short stories',
    broader: 'Language and literature',
    related: ['Literary criticism', 'Drama'],
  },
  {
    code: 'LL-04',
    label: 'Literary criticism',
    broader: 'Language and literature',
    related: ['Learning English', 'Short stories'],
  },
  {
    code: 'LL-05',
    label: 'Learning English',
    broader: 'Language and literature',
    related: ['Learning Danish', 'Literary criticism'],
  },
  {
    code: 'LL-06',
    label: 'Learning Danish',
    broader: 'Language and literature',
    related: ['Learning Spanish', 'Learning English'],
  },
  {
    code: 'LL-07',
    label: 'Learning Spanish',
    broader: 'Language and literature',
    related: ['Writing skills', 'Learning Danish'],
  },
  {
    code: 'LL-08',
    label: 'Writing skills',
    broader: 'Language and literature',
    related: ['Poetry', 'Learning Spanish'],
  },
  {
    code: 'ST-01',
    label: 'Programming',
    broader: 'Science and technology',
    related: ['Astronomy', 'Engineering'],
  },
  {
    code: 'ST-02',
    label: 'Astronomy',
    broader: 'Science and technology',
    related: ['Physics', 'Programming'],
  },
  {
    code: 'ST-03',
    label: 'Physics',
    broader: 'Science and technology',
    related: ['Chemistry', 'Astronomy'],
  },
  {
    code: 'ST-04',
    label: 'Chemistry',
    broader: 'Science and technology',
    related: ['Mathematics', 'Physics'],
  },
  {
    code: 'ST-05',
    label: 'Mathematics',
    broader: 'Science and technology',
    related: ['Electronics', 'Chemistry'],
  },
  {
    code: 'ST-06',
    label: 'Electronics',
    broader: 'Science and technology',
    related: ['Robotics', 'Mathematics'],
  },
  {
    code: 'ST-07',
    label: 'Robotics',
    broader: 'Science and technology',
    related: ['Climate science', 'Electronics'],
  },
  {
    code: 'ST-08',
    label: 'Climate science',
    broader: 'Science and technology',
    related: ['Engineering', 'Robotics'],
  },
  {
    code: 'ST-09',
    label: 'Engineering',
    broader: 'Science and technology',
    related: ['Programming', 'Climate science'],
  },
  {
    code: 'SM-01',
    label: 'Personal finance',
    broader: 'Society and money',
    related: ['Law for everyone', 'Community organising'],
  },
  {
    code: 'SM-02',
    label: 'Law for everyone',
    broader: 'Society and money',
    related: ['Politics', 'Personal finance'],
  },
  {
    code: 'SM-03',
    label: 'Politics',
    broader: 'Society and money',
    related: ['Careers', 'Law for everyone'],
  },
  {
    code: 'SM-04',
    label: 'Careers',
    broader: 'Society and money',
    related: ['Starting a business', 'Politics'],
  },
  {
    code: 'SM-05',
    label: 'Starting a business',
    broader: 'Society and money',
    related: ['Volunteering', 'Careers'],
  },
  {
    code: 'SM-06',
    label: 'Volunteering',
    broader: 'Society and money',
    related: ['Community organising', 'Starting a business'],
  },
  {
    code: 'SM-07',
    label: 'Community organising',
    broader: 'Society and money',
    related: ['Personal finance', 'Volunteering'],
  },
  {
    code: 'TO-01',
    label: 'Sailing',
    broader: 'Travel and outdoors',
    related: ['Hiking', 'Wild swimming'],
  },
  {
    code: 'TO-02',
    label: 'Hiking',
    broader: 'Travel and outdoors',
    related: ['Cycling', 'Sailing'],
  },
  {
    code: 'TO-03',
    label: 'Cycling',
    broader: 'Travel and outdoors',
    related: ['Camping', 'Hiking'],
  },
  {
    code: 'TO-04',
    label: 'Camping',
    broader: 'Travel and outdoors',
    related: ['Coastal towns', 'Cycling'],
  },
  {
    code: 'TO-05',
    label: 'Coastal towns',
    broader: 'Travel and outdoors',
    related: ['City guides', 'Camping'],
  },
  {
    code: 'TO-06',
    label: 'City guides',
    broader: 'Travel and outdoors',
    related: ['Maps and navigation', 'Coastal towns'],
  },
  {
    code: 'TO-07',
    label: 'Maps and navigation',
    broader: 'Travel and outdoors',
    related: ['Wild swimming', 'City guides'],
  },
  {
    code: 'TO-08',
    label: 'Wild swimming',
    broader: 'Travel and outdoors',
    related: ['Sailing', 'Maps and navigation'],
  },
];
