<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Fx.Conversion.Specs</RootNamespace>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Fx.Conversion.Core\Fx.Conversion.Core.csproj" />
    <ProjectReference Include="..\Fx.Conversion.TestSupport\Fx.Conversion.TestSupport.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Reqnroll.xunit.v3" />
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="xunit.v3.mtp-off" />
  </ItemGroup>

</Project>
