#!/usr/bin/env python3
"""Build (or rebuild) this training set from its bundles: verify every bundle, extract the readable snapshots, write
registry.json and the unit table of README.md.

    python3 tools/build_set.py --source-registry ../scanner-benchmark/registry.json \
        --baseline ../scanner-benchmark/results/watchdog/baseline-2026-10-07.json

Inputs: `units/<unit>.bundle` (made with `git bundle create units/<unit>.bundle --all` from the authoring clone after
`git fetch --tags`), the harness registry (every frozen version of every unit: tag, commit, keySha256), and the
baseline (language and family per unit). For every unit the bundle is cloned into a temporary directory and EVERY
registered tag must resolve to its registered commit with the registered key hash at `benchmark/answer-key.json`;
any mismatch aborts before anything is written. The snapshot `units/<unit>/` is `git archive <latestTag>` of that
clone (code at the frozen tag, no .git). Standard library only.
"""
import argparse
import hashlib
import io
import json
import os
import re
import shutil
import subprocess
import sys
import tarfile
import tempfile
from collections import OrderedDict

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
UNITS = os.path.join(ROOT, "units")
SET_REPO = "code-assurance-initiative/training-set-2026"
KEY_PATH = "benchmark/answer-key.json"


def git(repo, *args, binary=False):
    out = subprocess.run(["git", "-C", repo, *args], capture_output=True, check=True).stdout
    return out if binary else out.decode().strip()


def sha256_file(p):
    h = hashlib.sha256()
    with open(p, "rb") as f:
        for chunk in iter(lambda: f.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def phase_of(name):
    # the authoring programme's phases (scanner-benchmark PROGRESS): 1 = the two pilot C# units, 2 = C# units,
    # 3 = TypeScript units, 4 = the Quellbrook reference estate
    if name.startswith("estate-"):
        return 4
    if name in ("bench-csharp-baseline-clean", "bench-csharp-security-secrets"):
        return 1
    return 2 if name.startswith("bench-csharp-") else 3


def themes_from_readme(path):
    """unit -> short theme, from the harness README's repository table."""
    out = {}
    if not path or not os.path.exists(path):
        return out
    for line in open(path, encoding="utf-8"):
        m = re.match(r"^\| \[`([^`]+)`\]\([^)]*\) \| [^|]+ \| [^|]+ \| (.+?) \|\s*$", line)
        if m:
            out[m.group(1)] = m.group(2).strip()
    return out


LANG = {"csharp": "C#", "typescript": "TypeScript"}


def write_readme_table(units):
    rows = ["| Unit | Language | Family | Theme | Plants | Traps | Latest tag | Versions |",
            "|---|---|---|---|---:|---:|---|---|"]
    for u in units:
        rows.append(f"| [`{u['name']}`]({u['snapshot']}) | {LANG.get(u['language'], u['language'])} | {u['family']} | "
                    f"{u['theme']} | {u['labels']['must-fire']} | {u['labels']['must-not-fire']} | {u['latestTag']} | "
                    f"{', '.join(v['tag'] for v in u['versions'])} |")
    mf = sum(u["labels"]["must-fire"] for u in units)
    mnf = sum(u["labels"]["must-not-fire"] for u in units)
    rows.append(f"| **{len(units)} units** | | | | **{mf}** | **{mnf}** | | |")
    path = os.path.join(ROOT, "README.md")
    text = open(path, encoding="utf-8").read()
    begin, end = "<!-- BEGIN units (generated by tools/build_set.py) -->", "<!-- END units -->"
    i, j = text.index(begin) + len(begin), text.index(end)
    with open(path, "w", encoding="utf-8") as f:
        f.write(text[:i] + "\n" + "\n".join(rows) + "\n" + text[j:])


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--source-registry", required=True, help="scanner-benchmark/registry.json")
    ap.add_argument("--baseline", required=True, help="scanner-benchmark/results/watchdog/baseline-*.json")
    ap.add_argument("--themes", help="scanner-benchmark/README.md (its repository table supplies short themes)")
    ap.add_argument("--created", default="2026-10-07")
    a = ap.parse_args(argv)

    src = json.load(open(a.source_registry, encoding="utf-8"))
    base = json.load(open(a.baseline, encoding="utf-8"))
    meta = {r["name"]: r for r in base["repos"]}
    themes = themes_from_readme(a.themes)
    versions = OrderedDict()
    for e in src["repos"]:
        versions.setdefault(e["repo"].split("/")[1], []).append(e)

    units = []
    for name, vs in versions.items():
        bundle = os.path.join(UNITS, f"{name}.bundle")
        if not os.path.exists(bundle):
            raise SystemExit(f"{name}: {bundle} missing")
        subprocess.run(["git", "bundle", "verify", "-q", bundle], check=True, capture_output=True)
        tmp = tempfile.mkdtemp(prefix=f"ts-{name}-")
        try:
            clone = os.path.join(tmp, name)
            # a bare repository holding EVERY ref of the bundle (a plain clone would drop refs/remotes/*)
            subprocess.run(["git", "init", "-q", "--bare", clone], check=True, capture_output=True)
            subprocess.run(["git", "-C", clone, "fetch", "-q", bundle, "+refs/*:refs/*"], check=True,
                           capture_output=True)
            for v in vs:
                commit = git(clone, "rev-parse", f"refs/tags/{v['tag']}^{{commit}}")
                if commit != v["commit"]:
                    raise SystemExit(f"{name} {v['tag']}: bundle has {commit}, registry {v['commit']}")
                key = git(clone, "show", f"{v['tag']}:{KEY_PATH}", binary=True)
                if hashlib.sha256(key).hexdigest() != v["keySha256"]:
                    raise SystemExit(f"{name} {v['tag']}: key sha256 differs from the registry")
            latest = vs[-1]
            key = json.loads(git(clone, "show", f"{latest['tag']}:{KEY_PATH}", binary=True))
            snap = os.path.join(UNITS, name)
            if os.path.exists(snap):
                shutil.rmtree(snap)
            os.makedirs(snap)
            tar = git(clone, "archive", "--format=tar", latest["tag"], binary=True)
            with tarfile.open(fileobj=io.BytesIO(tar)) as t:
                t.extractall(snap, filter="tar")
            tags = git(clone, "tag", "--list").split()
            commits = int(git(clone, "rev-list", "--count", "--all"))
        finally:
            shutil.rmtree(tmp)
        labels = {}
        for e in key["entries"]:
            labels[e["label"]] = labels.get(e["label"], 0) + 1
        m = meta.get(name, {})
        units.append(OrderedDict(
            name=name,
            formerRepository=f"https://github.com/code-assurance-initiative/{name}",
            language=m.get("language") or "/".join(key.get("languages", [])),
            family=m.get("family"),
            phase=phase_of(name),
            theme=themes.get(name) or key.get("theme"),
            latestTag=latest["tag"],
            commit=latest["commit"],
            keySha256=latest["keySha256"],
            keyVersion=key.get("keyVersion"),
            labels=OrderedDict((k, labels.get(k, 0)) for k in
                               ("must-fire", "must-not-fire", "clean", "not-applicable", "score-band")),
            bundle=f"units/{name}.bundle",
            bundleSha256=sha256_file(bundle),
            bundleBytes=os.path.getsize(bundle),
            snapshot=f"units/{name}/",
            tagsInBundle=sorted(tags, key=lambda t: [int(x) for x in t.lstrip("v").split(".")]),
            commitsInBundle=commits,
            versions=[OrderedDict((k, v[k]) for k in ("tag", "commit", "keySha256", "frozenAt", "supersedes", "change",
                                                      "note") if k in v) for v in vs],
        ))
        print(f"{name:<36} {latest['tag']:<7} versions {len(vs)}  tags {len(tags)}  commits {commits}  "
              f"bundle {os.path.getsize(bundle):>8} B  OK")

    reg = OrderedDict(
        set=SET_REPO,
        setVersion="1.0.0",
        rubric="rubric-2026.10.1",
        created=a.created,
        format="1.0",
        keyPath=KEY_PATH,
        instrumentBaseline=OrderedDict(
            document="https://github.com/code-assurance-initiative/scanner-benchmark/blob/main/results/watchdog/"
                     "BASELINE-2026-10-07.md",
            data="https://github.com/code-assurance-initiative/scanner-benchmark/blob/main/results/watchdog/"
                 "baseline-2026-10-07.json",
            instrument=base.get("instrument")),
        harness="https://github.com/code-assurance-initiative/scanner-benchmark",
        units=units,
    )
    with open(os.path.join(ROOT, "registry.json"), "w", encoding="utf-8") as f:
        json.dump(reg, f, indent=1, ensure_ascii=False)
        f.write("\n")
    write_readme_table(units)
    print(f"wrote registry.json: {len(units)} units, {sum(len(u['versions']) for u in units)} registered versions")
    return 0


if __name__ == "__main__":
    sys.exit(main())
